const ADD_POST = 'ADD_POST';
const REMOVE_POST = 'REMOVE_POST';
const UPDATE_POST = 'UPDATE_POST';
const ADD_COMMENT = 'ADD_COMMENT';
const REMOVE_COMMENT = 'REMOVE_COMMENT';
const ADD_TITLE = 'ADD_TITLE';
const UPDATE_TITLE = 'UPDATE_TITLE';
const REMOVE_TITLE = 'REMOVE_TITLE';

export {
  ADD_POST,
  REMOVE_POST,
  UPDATE_POST,
  ADD_TITLE,
  UPDATE_TITLE,
  REMOVE_TITLE,
  ADD_COMMENT,
  REMOVE_COMMENT,
};
